packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  # Core dependencies
  typescript: ^5.3.0
  '@types/node': ^20.10.0
  
  # AI Libraries
  openai: ^4.67.0
  '@anthropic-ai/sdk': ^0.27.0
  
  # Web Framework
  express: ^4.19.0
  cors: ^2.8.5
  helmet: ^7.1.0
  
  # Database & Caching  
  prisma: ^5.20.0
  redis: ^4.7.0
  
  # Utilities
  winston: ^3.14.0
  zod: ^3.23.0
  dotenv: ^16.4.0
  
  # Development
  tsx: ^4.19.0
  jest: ^29.7.0
  eslint: ^9.12.0